name: Update Latest PRs
on:
  schedule:
    - cron: "30 3 * * *"  # Runs daily at 8:30 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          GH_USERNAME: ArjunJagdale
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: python .github/scripts/update_prs.py

      - name: Commit & Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update recent PRs" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/ArjunJagdale/ArjunJagdale.git HEAD:main
