name: Update Latest PRs

on:
  schedule:
    - cron: "0 3 * * *"  # every day at 8:30 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps & run script
        run: |
          npm install node-fetch
          node .github/scripts/update-prs.js

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update recent PRs" || echo "No changes to commit"
          git push
