name: Update Latest PRs
env:
  GH_PAT: ${{ secrets.GH_PAT }}

on:
  schedule:
    - cron: "0 3 * * *"  # every day at 8:30 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update README
        run: python .github/scripts/update_prs.py

      - name: Commit & Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "ArjunJagdale"
          git config user.email "vvcxlight@gmail.com"  # Can be any GitHub-verified email
          git add README.md
          git commit -m "chore: update recent PRs" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/ArjunJagdale/ArjunJagdale.git HEAD:main
